[package]
name = "luminance-examples-desktop"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Stateless and type-safe graphics framework"
keywords = ["stateless", "type-safe", "graphics", "luminance"]
categories = ["rendering::graphics-api"]
homepage = "https://github.com/phaazon/luminance-rs"
repository = "https://github.com/phaazon/luminance-rs"
documentation = "https://docs.rs/luminance"
readme = "README.md"
edition = "2021"
rust-version = "1.65.0"

[[bin]]
name = "luminance-examples-desktop"
path = "src/main.rs"

[features]
funtest = ["luminance-examples/funtest",]
funtest-gl33-f64-uniform = ["luminance-examples/funtest-gl33-f64-uniform"]

[dependencies]
env_logger = "0.9.0"
glfw = "0.50"
image = "0.24.1"
log = "0.4.11"
luminance = { version = "0.48.0-dev", path = "../../luminance", features = ["mint"] }
luminance-examples = { version = "0.1", path = "../common" }
luminance-gl2 = { version = "0.20.0-dev", path = "../../luminance-gl2" }
luminance-glfw = { version = "0.19.0-dev", path = "../../luminance-glfw" }
structopt = "0.3.21"
