language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq && sudo apt-get install -y libxrandr-dev xorg-dev; fi

script:
  - rustc --version
  - cargo --version
  - cargo build
  - cargo test
  # luminance examples
  - cd luminance/examples && cargo check --verbose
