[workspace]

members = [
  "luminance",
  "luminance-derive",
  "luminance-glfw",
  "luminance-windowing",
]

[patch.crates-io]
luminance-derive = { path = "./luminance-derive" }
luminance-glfw = { path = "./luminance-glfw" }
luminance-windowing = { path = "./luminance-windowing" }
