[package]
name = "luminance-std140"
version = "0.2.1"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Std140 types and trait for OpenGL-based luminance backends"
keywords = ["stateless", "type-safe", "graphics", "luminance", "std140"]
categories = ["rendering::graphics-api"]
homepage = "https://github.com/phaazon/luminance-rs"
repository = "https://github.com/phaazon/luminance-rs"
documentation = "https://docs.rs/luminance-std140"
readme = "README.md"
edition = "2021"
rust-version = "1.65.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
luminance = { version = ">=0.46, <0.48", path = "../luminance" }
